### ISSUE TITLE
Use deployment button on Github for pkgdown previews

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/education-workflows#9]
Something like this:

```yaml
      - name: Create Github "view deployment" button in PR
        if: ${{github.event_name == 'pull_request'}}
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.RELEASE_NAME }}
          ref: ${{ github.head_ref }}
          logs: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
```

followed by on success

```yaml
      - name: Update Github "view deployment" button in PR
        uses: bobheadxi/deployments@v1
        if: ${{ always() && github.event_name == 'pull_request'}}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: 'https://${{ steps.deployment.outputs.env }}/preview/pr${{ env.pr_number }}'
          logs: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
```
